from tkinter import *
root = Tk()
content = Frame(root)
frame = Frame(content, bg="gray40", borderwidth=3, relief="sunken",
    width=200, height=100)
namelbl = Label(content, bg="green", text="Name")
name = Entry(content)
onevar = BooleanVar()
twovar = BooleanVar()
threevar = BooleanVar()
onevar.set(True)
twovar.set(False)
threevar.set(True)
one = Checkbutton(content, text="One", variable=onevar, onvalue=True)
two = Checkbutton(content, text="Two", variable=twovar, onvalue=True)
three = Checkbutton(content, text="Three", variable=threevar, onvalue=True)
ok = Button(content, text = "Okay")
cancel = Button(content, text="Cancel")
content.grid(row=0, column=0,sticky=NSEW)
frame.grid( row=0, column=0, columnspan=3, rowspan=2, sticky=NSEW)

namelbl.grid(row=0, column=3, columnspan=2, sticky=NSEW)
name.grid( row=1, column=3, columnspan=2, sticky=NSEW)

one.grid(row=3, column=0, sticky=NSEW)
two.grid(row=3, column=1, sticky=NSEW)
three.grid(row=3, column=2, sticky=NSEW)
ok.grid( row=3,column=3, sticky=NSEW)
cancel.grid(row=3,column=4, sticky=NSEW)

root.grid_rowconfigure(0, weight=1 )
root.grid_columnconfigure(0, weight= 1)
content.grid_rowconfigure(0, weight= 1)
content.grid_columnconfigure(0, weight= 1)
